/// <reference types="@quasar/app-vite/client" />

declare module '@carbon/icons-vue/es/checkbox/16'
declare module '@carbon/icons-vue/es/checkbox/24'
declare module '@carbon/icons-vue/es/checkbox--checked/16'
declare module '@carbon/icons-vue/es/checkbox--checked/24'
declare module '@carbon/icons-vue/es/location/16'
declare module '@carbon/icons-vue/es/email/16'
declare module '@carbon/icons-vue/es/phone/16'
declare module '@carbon/icons-vue/es/construction/16'
declare module '@carbon/icons-vue/es/calendar/16'
declare module '@carbon/icons-vue/es/currency--dollar/16'
declare module '@carbon/icons-vue/es/alarm/16'
declare module '@carbon/icons-vue/es/add--alt/16'
declare module '@carbon/icons-vue/es/checkmark--outline/16'
declare module '@carbon/icons-vue/es/pending/16'
declare module '@carbon/icons-vue/es/undefined/16'
