export const calendarView = (state) => state.calendarView
export const selectedDate = (state) => state.selectedDate
export const locale = (state) => state.locale
export const maxDays = (state) => state.maxDays
export const fiveDayWorkWeek = (state) => state.fiveDayWorkWeek
export const firstDayMonday = (state) => state.firstDayMonday
export const shortMonthLabel = (state) => state.shortMonthLabel
export const showDayOfYearLabel = (state) => state.showDayOfYearLabel
export const shortWeekdayLabel = (state) => state.shortWeekdayLabel
export const shortIntervalLabel = (state) => state.shortIntervalLabel
export const hour24Format = (state) => state.hour24Format
export const hideHeader = (state) => state.hideHeader
export const noScroll = (state) => state.noScroll
export const showMonthLabel = (state) => state.showMonthLabel
export const showWorkWeeks = (state) => state.showWorkWeeks
export const intervalRange = (state) => state.intervalRange
export const intervalRangeStep = (state) => state.intervalRangeStep
export const intervalHeight = (state) => state.intervalHeight
export const dayHeight = (state) => state.dayHeight
export const enableThemes = (state) => state.enableThemes
export const theme = (state) => state.theme
