export default {
  calendarView: 'day',
  selectedDate: '2019-04-01',
  locale: 'en-us',
  maxDays: 1,
  bordered: false,
  fiveDayWorkWeek: false,
  firstDayMonday: false,
  shortMonthLabel: false,
  showDayOfYearLabel: false,
  shortWeekdayLabel: false,
  shortIntervalLabel: false,
  hour24Format: false,
  hideHeader: false,
  noScroll: false,
  showMonthLabel: true,
  showWorkWeeks: false,
  noDefaultHeaderBtn: false,
  noDefaultHeaderText: false,
  intervalRange: { min: 0, max: 24 },
  intervalRangeStep: 1,
  intervalHeight: 60,
  resourceHeight: 60,
  resourceWidth: 100,
  dayHeight: 100
}
